export interface rnInfo {
	demoid: string;
  orgid: string;
	rnid: string;
	firstName: string;
	lastName: string;
	Submitted: string;
	//"Participation TYPE": string;
	datehired: string;
	unittypedesc: string;
	Organizationemailaddress: string;
	EmploymentStartdate: string;
	// age: string;
	// Gender: string;
	// bacdrgrcvdfm: string;
	// DrgRcvd: string;
	// drgrcvdothspc: string;
	// PrvNonNrDrg: string;
	// prvnonnrmajor: string;
	// GPA: string;
	// Experience: string;
	// LANGUAGE: string;
	// PrvHirFacEmp: string;
	// PrvNrAssist: string;
	// PrvHomHlthAide: string;
	// PrvLPN: string;
	// PrvPatCareTech: string;
	// PrvEMT: string;
	// PrvStudent: string;
	// PrvHirFacStd: string;
	// PrvSenior: string;
	// PrvHirFacCliRot: string;
	// PrvAcuteCare: string;
	// PrvLongTrmCare: string;
	// PrvRehab: string;
	// PrvRefProg: string;
	// PrvNone: string;
	// PrvOther: string;
	// prvotherspc: string;
	// shortname: string;
	active: string;
	Terminated: string;
	ABSENT: string;
}